/** Japanese UI copy. Section titles / tab names stay English in components. */

export const UI = {
  common: {
    cefr: 'CEFR',
    scene: 'シーン',
    level: 'レベル',
    mode: 'モード',
    delete: '削除',
    save: '保存',
    back: '← 戻る',
    loading: '読み込み中…',
    audioSaved: '音声保存済',
    recommendedHint: '★ = 選択中の CEFR 帯の推奨レベル',
    syncFromDrive: ' Google Drive から同期されます。',
    syncAudioFromDrive: ' 音声は Google Drive から取得できます。',
  },
  settings: {
    open: '設定',
    close: '閉じる',
    cloudSyncSub: 'クラウド同期',
    cloudSyncHint: '過去の問題・Speech・音声は Google Drive に自動保存されます。',
    status: '状態',
    statusLabels: {
      disabled: '利用不可',
      idle: '待機中',
      syncing: '同期中…',
      synced: '同期済み',
      error: 'エラー',
    },
    anthropicSub: 'Anthropic API',
    anthropicHint: 'API キーはこのブラウザにのみ保存されます。',
    apiKeyLabel: 'Anthropic API Key',
    clearKey: 'キーを削除',
    registerKeyHint: 'Settings で Anthropic API キーを登録すると、新しい文を生成できます。',
  },
  intensive: {
    start: 'セッション開始',
    needKeyHint: '新しい文の生成には API キーが必要です。過去の問題はキーなしで再生できます。',
    lv5Hint: 'Lv5（対話）は Cloze と Full Dictation のみ対応です。',
    replayCount: '再生回数',
    checkAnswer: '答え合わせ',
    typeWhatYouHear: '聞こえたとおりに入力…',
    mpMissing: '生成データに minimal_pair_target がありません。',
    loadingGenerate: '文を生成中…',
    loadingAudio: '音声を合成中…',
    loadingCached: 'キャッシュ音声を読み込み中…',
    fetchingAudio: '音声を取得中…',
    historyHint: '練習済みの文を再生できます。初回再生後はブラウザに音声が保存されます。',
    practice: '練習',
    score: 'スコア',
    listenAgain: '▶ もう一度聞く',
    youChose: 'あなたの選択',
    correctWord: '正解',
    edits: '編集',
    words: '語',
    blank: '（未入力）',
    addToShadowing: 'シャドーイングキューに追加',
    addedToShadowing: 'シャドーイングキューに追加しました。',
    nextItem: '次の問題',
    sameAgain: '同じ問題をもう一度',
    backToSetup: 'セットアップに戻る',
  },
  extensive: {
    contentLength: 'コンテンツ長',
    structureFocus: '構造フラッグ（input flooding）',
    viewMode: '表示モード',
    readListen: '読みながら聞く',
    listenOnly: '聞くだけ',
    start: '多聴を開始',
    needKeyHint: 'Settings で Anthropic API キーを登録すると、新しいパッセージを生成できます。',
    loadingFirst: '最初のパッセージを生成中…',
    loadingAudio: '音声を読み込み中…',
    loadingCached: 'キャッシュ音声を読み込み中…',
    speed: '速度',
    auto: '自動',
    addToShadowing: 'シャドーに追加',
    setup: 'セットアップ',
    swipeHint: '上下スワイプで前後のパッセージへ',
    historyHint: '聴いたパッセージを再生できます。初回再生後はブラウザに音声が保存されます。',
    open: '開く',
    statsTotal: '合計',
    statsPassages: 'パッセージ',
    statsMin: '分',
    tapTranslation: 'タップで訳文を',
    show: '表示',
    hide: '非表示',
  },
  shadowing: {
    queueHint: '多聴・精聴から送られたパッセージがここに表示されます。',
    queueEmpty: 'キューは空です。',
    complete: '完了',
    practice: '練習',
    remove: '削除',
    structureFlags: '構造フラグ',
    generatePractice: '生成して練習',
    generating: '生成中…',
    backQueue: '← キュー',
    syncStage: 'スクリプト表示のまま小声で追う',
    shadowStage: 'スクリプト非表示で音声に追従',
    prosodyStage: '強勢・連結を意識して追う',
    shadowHint: 'モデル音声の直後に追って発声してください。',
    modelPlay: '▶ モデル',
    recordCompare: '録音と照合',
    startRecording: '録音開始',
    stopRecording: '停止',
    model: 'モデル',
    you: '自分',
    play: '▶ 再生',
    sttLabel: 'STT 認識結果',
    sttPlaceholder: '録音しながら認識されるか、手入力で修正…',
    compare: 'スクリプトと照合',
    analyzing: '分析中…',
    matchScore: '一致率',
    needScore: '必要',
    recognized: '認識',
    recordingHistory: '録音履歴',
    stage: 'Stage',
  },
  length: {
    short_passage: { label: '短いパッセージ', description: '3〜6文' },
    long_passage: { label: '長いパッセージ', description: '5〜8文' },
    dialogue: { label: '対話', description: '4〜8ターン' },
  },
};
