/** Japanese UI copy. Section titles / tab names stay English in components. */

export const UI = {
  common: {
    cefr: 'CEFR',
    scene: 'シーン',
    sceneRandom: 'ランダム',
    level: 'レベル',
    mode: 'モード',
    delete: '削除',
    save: '保存',
    back: '← 戻る',
    loading: '読み込み中…',
    audioSaved: '音声保存済',
    recommendedHint: '★ = 選択中の CEFR 帯の推奨レベル',
    syncFromDrive: ' Google Drive から同期されます。',
    syncAudioFromDrive: ' 音声は Google Drive から取得できます。',
  },
  settings: {
    open: '設定',
    close: '閉じる',
    cloudSyncSub: 'クラウド同期',
    cloudSyncHint: '精聴・多聴・シャドーの Past items、多聴の進捗統計、Speech、音声は Google Drive に自動保存されます。',
    status: '状態',
    statusLabels: {
      disabled: '利用不可',
      idle: '待機中',
      syncing: '同期中…',
      synced: '同期済み',
      error: 'エラー',
    },
    anthropicSub: 'Anthropic API',
    anthropicHint: 'API キーはこのブラウザにのみ保存されます。',
    apiKeyLabel: 'Anthropic API Key',
    clearKey: 'キーを削除',
    registerKeyHint: 'Settings で Anthropic API キーを登録すると、新しい文を生成できます。',
    audioCacheSub: 'Drive 音声キャッシュ',
    audioCacheHint: '同じ文を2回取得し、2回目が Drive キャッシュ HIT になるか検証します。',
    audioCacheLast: '直近の音声取得',
    audioCacheVerify: 'キャッシュを検証',
    audioCacheVerifying: '検証中…',
    audioCachePass: 'OK — 2回目は Drive キャッシュ HIT',
    audioCacheFail: '未確認 — 2回目も新規生成でした（GAS 再デプロイを確認）',
    audioCacheManifest: 'Manifest エントリ',
    audioCacheAccess: '累計 access_count',
    audioCacheCleanup: 'Manifest クリーンアップ',
    audioCacheCleaning: 'クリーンアップ中…',
    audioCacheCleanupDone: 'クリーンアップ完了',
    warmupSub: 'Warmup キャッシュ（事前生成）',
    warmupHint: 'CEFR × シーン × レベル × シェル向けに TTS キャッシュを事前投入します。1バッチずつ、または一括実行できます。',
    warmupProgress: '進捗',
    warmupSentencesPerCell: 'セルあたりの文数',
    warmupRunBatch: '1バッチ実行',
    warmupRunAll: '完了まで実行',
    warmupReset: '進捗リセット',
    warmupRunning: '実行中…',
    warmupDone: 'Warmup 完了',
    warmupPartial: 'Warmup 中断（続きは 1バッチ実行）',
    warmupResetDone: 'Warmup 進捗をリセットしました',
  },
  intensive: {
    start: 'セッション開始',
    needKeyHint: '新しい文の生成には API キーが必要です。過去の問題はキーなしで再生できます。',
    lv5Hint: 'Lv5（対話）は Cloze と Full Dictation のみ対応です。',
    replayCount: '再生回数',
    checkAnswer: '答え合わせ',
    typeWhatYouHear: '聞こえたとおりに入力…',
    mpMissing: '生成データに minimal_pair_target がありません。',
    loadingGenerate: '文を生成中…',
    loadingAudio: '音声を合成中…',
    loadingCached: 'キャッシュ音声を読み込み中…',
    fetchingAudio: '音声を取得中…',
    historyHint: '練習済みの文を再生できます。初回再生後はブラウザに音声が保存されます。',
    practice: '練習',
    score: 'スコア',
    listenAgain: '▶ もう一度聞く',
    youChose: 'あなたの選択',
    correctWord: '正解',
    edits: '編集',
    words: '語',
    blank: '（未入力）',
    addToShadowing: 'シャドーイングキューに追加',
    addedToShadowing: 'シャドーイングキューに追加しました。',
    shadowCandidateHint: 'Cloze 80% 以上 — 理解済みとしてシャドー候補に追加します。',
    shadowCandidateAdded: '理解済み — シャドーイングキューに追加済みです。',
    nextItem: '次の問題',
    sameAgain: '同じ問題をもう一度',
    backToSetup: 'セットアップに戻る',
  },
  extensive: {
    contentLength: 'コンテンツ長',
    structureFocus: '構造フラッグ（input flooding）',
    structureFocusHint: 'ON にすると各構造が文の 80% 以上に含まれるよう自動検証します（不合格は再生成）。',
    sceneRandomHint: '再生ごとにシーンを自動で変えます（自動 ON でも毎回ランダム）。',
    viewMode: '表示モード',
    readListen: '読みながら聞く',
    listenOnly: '聞くだけ',
    start: '多聴を開始',
    needKeyHint: 'Settings で Anthropic API キーを登録すると、新しいパッセージを生成できます。',
    loadingFirst: '最初のパッセージを生成中…',
    loadingAudio: '音声を読み込み中…',
    loadingCached: 'キャッシュ音声を読み込み中…',
    speed: '速度',
    auto: '連続再生',
    autoOn: 'ON',
    autoOff: 'OFF',
    autoAriaOn: '連続再生はオンです。タップでオフにします',
    autoAriaOff: '連続再生はオフです。タップでオンにします',
    loadingNext: '次のパッセージを準備中…',
    loadingNextFailed: '次のパッセージを読み込めませんでした',
    addToShadowing: 'シャドーに追加',
    addToShadowingDone: '✓ 追加済み',
    addToShadowingAdded: '✓ シャドーに追加',
    shadowQueueFull: 'キューが満杯です。シャドー画面で整理してください。',
    swipeHint: '上下スワイプで前後のパッセージへ',
    backgroundHint: '連続再生 ON でバックグラウンド・ロック画面でも再生を継続します（ホーム画面に追加推奨）',
    historyHint: '聴いたパッセージを再生できます。初回再生後はブラウザと Google Drive に音声が保存されます。',
    historyPlayAll: 'すべて聴き流す',
    historyPlaySelect: '選択して聴き流す',
    historySelectAll: '全選択',
    historySelectNone: '解除',
    historyPlaySelected: '選択を再生',
    historySelectCancel: 'キャンセル',
    historyPlaylistNow: '聴き流し再生中',
    historyPlaylistLoading: '音声を読み込み中…',
    historyPlaylistPlaying: '再生中',
    historyPlaylistStop: '停止',
    historyPlaylistSkip: '次へ',
    audioPause: '一時停止',
    audioResume: '再生',
    audioReplay: '最初から再生',
    open: '開く',
    statsTotal: '合計',
    statsPassages: 'パッセージ',
    statsMin: '分',
    statsStructureCompliance: '構造検証合格率',
    statsStructureEncounter: '接触',
    statsStructureTimes: '回',
    statsChunksHeading: 'チャンク遭遇',
    statsChunksTop: '上位チャンク',
    statsChunksRecent: '最近遭遇（24h）',
    statsChunksViewAll: 'すべて見る',
    statsChunksContexts: '文脈',
    statsChunksEmpty: 'まだチャンク遭遇データがありません。',
    tapTranslation: 'タップで訳文を',
    show: '表示',
    hide: '非表示',
  },
  shadowing: {
    queueHint: '多聴・精聴から送られたパッセージがここに表示されます。端末間で自動同期されます。',
    understoodBadge: '理解済み',
    queueEmpty: 'キューは空です。',
    complete: '完了',
    practice: '練習',
    remove: '削除',
    structureFlags: '構造フラグ',
    generatePractice: '生成して練習',
    generating: '生成中…',
    backQueue: '← キュー',
    syncStage: 'スクリプト表示のまま小声で追う',
    shadowStage: 'スクリプト非表示で音声に追従',
    prosodyStage: '強勢・連結を意識して追う',
    prosodyHint: 'ハイライトは target_features（弱形・連結・縮約）に基づきます。',
    shadowHint: 'モデル音声の直後に追って発声してください。',
    modelPlay: '▶ モデル',
    recordCompare: '録音と照合',
    startRecording: '録音開始',
    stopRecording: '停止',
    model: 'モデル',
    you: '自分',
    play: '▶ 再生',
    sttLabel: 'STT 認識結果',
    sttPlaceholder: '録音しながら認識されるか、手入力で修正…',
    compare: 'スクリプトと照合',
    analyzing: '分析中…',
    matchScore: '一致率',
    needScore: '必要',
    recognized: '認識',
    recordingHistory: '録音履歴',
    stage: 'Stage',
  },
  length: {
    short_passage: { label: '短いパッセージ', description: '3〜6文' },
    long_passage: { label: '長いパッセージ', description: '5〜8文' },
    dialogue: { label: '対話', description: '4〜8ターン' },
  },
};
